layouts:
  - tall
  - tall-right
  - fullscreen
  - column
mod1:
  - option
  - control
mod2: 
  - shift
  - option
floating:
  - ru.keepcoder.Telegram
  - com.spotify.client
  - com.apple.systempreferences
  - com.apple.finder
  - com.apple.FontBook

# shortcuts
shrink-main:
  mod: mod1
  key: j
expand-main:
  mod: mod1
  key: k
focus-ccw:
  mod: mod1
  key: h
focus-cw:
  mod: mod1
  key: l
swap-ccw:
  mod: mod2
  key: H
swap-cw:
  mod: mod2
  key: L
swap-main:
  mod: mod1
  key: enter
throw-space-left:
  mod: mod1
  key: left
throw-space-right:
  mod: mod1
  key: right
throw-screen-1:
  mod: mod1
  key: z
throw-screen-2:
  mod: mod1
  key: x
focus-screen-ccw:
  mod: mod1
  key: .
