layouts:
  - tall
  - tall-right
  - fullscreen
  - column
mod1:
  - option
  - control
mod2: 
  - shift
  - option
mod3: 
  - shift
  - option
  - control
floating:
  - ru.keepcoder.Telegram
  - com.spotify.client
  - com.apple.systempreferences
  - com.apple.finder
  - com.apple.FontBook

# shortcuts
shrink-main:
  mod: mod1
  key: j
expand-main:
  mod: mod1
  key: k
focus-ccw:
  mod: mod1
  key: h
focus-cw:
  mod: mod1
  key: l
swap-ccw:
  mod: mod2
  key: h
swap-cw:
  mod: mod2
  key: l
swap-screen-ccw:
  mod: mod3
  key: h
swap-screen-cw:
  mod: mod3
  key: l
swap-main:
  mod: mod1
  key: enter
throw-space-left:
  mod: mod1
  key: left
throw-space-right:
  mod: mod1
  key: right
throw-screen-1:
  mod: mod1
  key: z
throw-screen-2:
  mod: mod1
  key: x
focus-screen-ccw:
  mod: mod1
  key: c
increase-main:
  mod: mod1
  key: ","
decrease-main:
  mod: mod1
  key: .
select-tall-layout:
  mod: mod1
  key: a
select-tall-right-layout:
  mod: mod1
  key: s
select-column-layout:
  mod: mod1
  key: d
select-fullscreen-layout:
  mod: mod1
  key: f

